import { CheckCircle2, Clock3, FileSignature, ShieldX } from "lucide-react"
import { getAgent } from "@/lib/sentinel-data"
import { getAuditEvents } from "@/lib/server/store"

const statusIcons = {
  success: CheckCircle2,
  signed: FileSignature,
  pending: Clock3,
  blocked: ShieldX,
}

export async function AuditLedger() {
  const auditEvents = await getAuditEvents()

  return (
    <section className="px-4 pb-24 md:px-8">
      <div className="mx-auto max-w-7xl">
        <div className="mb-8 grid gap-4 border-b border-black/25 pb-8 lg:grid-cols-[0.8fr_1fr] lg:items-end">
          <h2 className="font-serif text-4xl font-black uppercase leading-none md:text-6xl">Signed event trail</h2>
          <p className="max-w-3xl font-mono text-sm leading-7 text-black/70">
            Each row records the agent, status, time, and proof output generated by the protected action path.
          </p>
        </div>

        <div className="divide-y divide-black/20 border-y border-black/25">
        {auditEvents.map((event) => {
          const agent = getAgent(event.agentId)
          const Icon = statusIcons[event.status] ?? FileSignature
          return (
            <article
              key={event.id}
              className="grid gap-5 py-6 md:grid-cols-[90px_minmax(0,1fr)_150px_minmax(0,1.1fr)] md:items-start"
            >
              <div className="font-mono text-sm uppercase text-black/60">{event.time}</div>
              <div>
                <div className="font-serif text-3xl uppercase leading-none md:text-4xl">{event.action}</div>
                <p className="mt-3 break-all font-mono text-xs uppercase text-black/55">{agent.did}</p>
              </div>
              <div className="flex items-center gap-2 font-mono text-xs uppercase text-black/70">
                <Icon className="h-5 w-5" />
                {event.status}
              </div>
              <div className="break-words font-mono text-sm leading-7 text-black/75">{event.proof}</div>
            </article>
          )
        })}
        </div>
      </div>
    </section>
  )
}
